### PR TITLE
English translations

### PR DESCRIPTION
**Pull request by niknetniko**
This PR adds English translations to the app. Services available in English:
- Resto menu: for now there is one English menu, which becomes the default on English devices. However, the university apparently plans to make all menus available in English next year.
- Minerva, depending on the language of the course in Minerva itself
- Libraries
- Info

Currently not available:
- Schamper
- Urgent.fm
- DSA stuff, like official news and events. The news is possible, since English news exists, but is currently not offered by the API.

This PR also cleans up some unused resources.

### CODE REVIEW

**Comment by redfast00** [comment]
Looks good, thank you!

The word "overmorrow" seems a bit strange (see https://english.stackexchange.com/a/45414).

**Comment by niknetniko** [comment]
I agree, but I didn't find anything better, as "day after tomorrow" seemed a bit long:
knipsel

**Comment by redfast00** [comment]
That does indeed look too long. Another option is to remove 'overmorrow/overmorgen' and just use the name of the day after 'tomorrow'. Yet another option is to keep it only in Dutch, but I suspect that would lead to ugly code. I don't know how many foreign students know of the word 'overmorrow', but then again, it would be pretty clear from the context.

**Comment by redfast00** [comment]
That's pretty neat.

**Pull request merged**
