### PR TITLE
Package by feature

### PR DESCRIPTION
**Pull request by niknetniko**
- Update some dependencies
- Move to a "package by feature" organisation. This means we put all classes for the same feature together. This is well explained in http://olivergierke.de/2013/01/whoops-where-did-my-architecture-go/. In theory, the goal is to come to a state where if we want to remove a feature, we delete one package and be done with it. In reality it's not that simple, but it remains the goal to put as much as possible in the packages.

### CODE REVIEW

**Comment by wschella** [comment]
I like it. This will seriously improve the ability for new coders to find their way in a large code base, and allow everybody to keep a nice overview. 

Ironically, I had some trouble finding where the sidenav/drawer code was located.

**Comment by niknetniko** [comment]
Yeah, perhaps it should move from common/main to a new top-level package called "home" or something?

**Comment by wschella** [comment]
I think MainActivity could just be in the root of hydra/common/, or even in just in the root of hydra/.
The other files there might be more fit in the utils, or a varia package?

**Comment by niknetniko** [comment]
That's even better 😄 I'll probably just make the two interfaces, `ArgumentsReceiver` and `ScheduledRemovalListener` _inner_ interfaces of MainActivity, since they are only meant to be used with that activity.

**Comment by wschella** [comment]
Great!

**Comment by niknetniko** [comment]
See #251

**Pull request merged**
