### PR TITLE
Enable accessing historic resto menu

### PR DESCRIPTION
**Pull request by niknetniko**
**Main**
Add a new activity allowing the user to browse historic resto menus.
I'm not sure how useful it is or how much it will be used, but 
1) We have the API, so why not use it?
2) There has been at least _one_ occasion where I wanted something like this

**Other**
- Fix some layout issues where the menu would be hidden underneath the buttons on smaller screens
- Make the text of the resto selector bolder, as it should be.
- Clean up some stuff

### CODE REVIEW

**Comment by niknetniko** [comment]
Screenshot:
device-2018-02-25-220754

**Comment by wschella** [comment]
Would this be a new item in the sidenav? Might clutter things a bit then.

**Comment by niknetniko** [comment]
No, since it will probably not be used that much, I put it in the app bar (the second icon from the right)
screenshot_20180226-103520

**Comment by wschella** [comment]
Perfect!

**Pull request merged**
